# See https://pre-commit.ci for more information
# pre-commit.ci config to automatically run pre-commit hooks on PRs

ci:
  # Run pre-commit autoupdate monthly
  autoupdate_schedule: monthly

  # Skip pyright hook in CI - it requires the package to be installed
  skip: [pyright]

  # Automatically fix issues and commit
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci

  autofix_prs: true

  # Create PR for autoupdate
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
