language: python
sudo: false

matrix:
    include:
        - python: "3.6"
          env: TOXENV=lint
        - python: "2.7"
          env: TOXENV=py27
        - python: "3.6"
          env: TOXENV=py36
        - python: "3.7"
          env: TOXENV=py37
          dist: xenial
        - python: "pypy"
          env: TOXENV=pypy
        - python: "pypy3"
          env: TOXENV=pypy
    allow_failures:
        - python: "pypy"
          env: TOXENV=pypy
        - python: "pypy3"
          env: TOXENV=pypy

install:
    - travis_retry pip install -U pip setuptools zc.buildout
    - travis_retry buildout -c buildout.cfg
    - travis_retry pip install tox coveralls coverage

script:
    - travis_retry tox

after_success:
    - coverage combine
    - coveralls

notifications:
    email: false

cache:
  pip: true
